### ISSUE TITLE
ModuleNotFoundError: No module named 'anytree'

### ISSUE THREAD

**Issue by aneshmut** [IvanReznikov/bk_clustering#35]
Hello Ivan
This clustering technique looks promising. I am trying to use it for customer segmentation. I am getting "ModuleNotFoundError: No module named 'anytree'". I looked into the code and I don't see any "anytree" module in the directory. Please let me know how to resolve this.

**Comment by IvanReznikov** [comment]
try pip install anytree. I'll include that in the prerequisites.
Thanks!
